name: "CARATEC BMS BLE"
version: "2.1.0"
slug: "caratec_batteries"
description: "CARATEC Batterien über BLE auslesen"
arch: [aarch64]
init: false
host_network: true
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
apparmor: false
host_dbus: true
environment:
  DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/run/dbus/system_bus_socket"
options:
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: "mqtt"
  mqtt_pass: "mqtt"
  poll_interval: 5
  batteries:
    - name: "battery_1"
      address: "10:23:81:8B:13:1A"
    - name: "battery_2"
      address: "10:23:81:8B:13:AD"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_pass: password
  poll_interval: int(1,60)
  batteries:
    - name: str
      address: str